# Generated by Django 2.2.7 on 2019-11-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Techer_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_initial', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=120)),
                ('faculty', models.CharField(max_length=120)),
                ('email_info', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=120)),
                ('dept_belong', models.ForeignKey(on_delete='DO_NOTHING', to='allinfo.All_department', verbose_name='Category')),
            ],
        ),
    ]
