# Generated by Django 2.2.7 on 2019-11-29 10:08

import allinfo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allinfo', '0002_techer_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='techer_info',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=allinfo.models.upload_image_path),
        ),
        migrations.AlterField(
            model_name='techer_info',
            name='name_initial',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
