# Generated by Django 2.2.7 on 2019-12-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allinfo', '0003_auto_20191129_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techer_info',
            name='dept_belong',
            field=models.ForeignKey(on_delete='DO_NOTHING', to='allinfo.All_department', verbose_name='Department'),
        ),
    ]
