# Generated by Django 2.2.7 on 2019-12-08 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allinfo', '0004_auto_20191201_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='techer_info',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='techer_info',
            name='dept_belong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='allinfo.All_department'),
        ),
    ]
