# Generated by Django 2.2.7 on 2019-12-08 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routine_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_with_na',
            name='routine_days',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='routine_info.Routine_days'),
        ),
        migrations.AlterField(
            model_name='room_with_na',
            name='routine_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='routine_info.Routine_time'),
        ),
        migrations.AlterField(
            model_name='room_with_na',
            name='teacher_initial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='allinfo.Techer_info'),
        ),
    ]
